function data = load_data()
    datap = import_readme(fullfile('../', 'README-991p73A-ZPositive.md'));
    datap.segmodels = cell(size(datap.names));
    for ii=1:length(datap.names)
        name = datap.names{ii};
        filename = fullfile('../', name, 'M1', '0991p63A','z-positive', 'model.out');
        datap.segmodels{ii} = import_model(filename);
    end
    
    datan = import_readme(fullfile('../', 'README-991p73A-ZNegative.md'));
    datan.segmodels = cell(size(datan.names));
    for ii=1:length(datan.names)
        name = datan.names{ii};
        filename = fullfile('../', name, 'M1', '0991p63A','z-negative', 'model.out');
        datan.segmodels{ii} = import_model(filename);
    end
    
    data.names = datap.names;
    data.angle = datap.angle + datan.angle;
    data.int_dip = datap.int_dip + datan.int_dip;
    data.int_quad = datap.int_quad + datan.int_quad;
    data.int_sext = datap.int_sext + datan.int_sext;
    data.rx_init = datap.rx_init;
    
    data.segmodels = cell(size(data.names));
    for i=1:length(datap.segmodels)
        data.segmodels{i} = [fliplr(datan.segmodels{i}), datap.segmodels{i}];
    end
end


function model = import_model(filename)

    %% Code generated by matlab
    % Initialize variables.
    delimiter = ',';
    startRow = 3;
    endRow = inf;

    % Read columns of data as text:
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%s%s%s%s%s%s%s%s%s%[^\n\r]';
    % Open the text file.
    fileID = fopen(filename,'r');

    % Read columns of data according to the format.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for block=2:length(startRow)
        frewind(fileID);
        dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
        for col=1:length(dataArray)
            dataArray{col} = [dataArray{col};dataArrayBlock{col}];
        end
    end
    fclose(fileID);

    raw = import_numeric_data(dataArray, [1,2,3,4,5,6,7,8,9]);
    
    % Create output variable
    segmodel = cell2mat(raw);

    %% Adapted by Fernando
    % Creates AT model
    monomials = [0,1,2,3,4,5,6];
    passmethod = 'BndMPoleSymplectic4Pass';
    famname = 'B';

    % converts deflection angle from degress to radians
    segmodel(:,2) = segmodel(:,2) * (pi/180.0);

    % builds half of the magnet model
    b = zeros(1,size(segmodel,1));
    maxorder = 1+max(monomials);
    for i=1:size(segmodel,1)
        PolyB = zeros(1,maxorder); PolyA = zeros(1,maxorder);
        PolyB(monomials+1) = segmodel(i,3:end);
        b(i) = rbend_sirius(famname, segmodel(i,1), segmodel(i,2), 0, 0, 0, 0, 0, PolyA, PolyB, passmethod);
    end

    % builds entire magnet model, inserting additional markers
    % model_length = 2*sum(segmodel(:,2));
    model = buildlat(b);
end

function data = import_readme(filename)

    %% Code generated by matlab
    % Initialize variables.
    delimiter = {',','|'};
    startRow = 8;
    endRow = inf;

    % Read columns of data as text:
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%*s%s%s%s%s%s%s%[^\n\r]';
    % Open the text file.
    fileID = fopen(filename,'r');

    % Read columns of data according to the format.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    textscan(fileID, '%[^\n\r]', startRow(1)-1, 'WhiteSpace', '', 'ReturnOnError', false);
    dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for block=2:length(startRow)
        frewind(fileID);
        textscan(fileID, '%[^\n\r]', startRow(block)-1, 'WhiteSpace', '', 'ReturnOnError', false);
        dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'ReturnOnError', false, 'EndOfLine', '\r\n');
        for col=1:length(dataArray)
            dataArray{col} = [dataArray{col};dataArrayBlock{col}];
        end
    end

    % Close the text file.
    fclose(fileID);

    raw = import_numeric_data(dataArray, [2,3,4,5,6]);

    % Split data into numeric and cell columns.
    rawNumericColumns = raw(:, [2,3,4,5,6]);
    rawCellColumns = raw(:, 1);


    %% Adapted by Fernando
    % Allocate imported array to column variable names
    names = rawCellColumns(:, 1);

    for ii=1:length(names)
        name = names{ii};
        names{ii} = strip(name(1:end-1), '*');
    end

    data.names = names;
    data.angle = cell2mat(rawNumericColumns(:, 1));
    data.int_dip = cell2mat(rawNumericColumns(:, 2));
    data.int_quad = cell2mat(rawNumericColumns(:, 3));
    data.int_sext = cell2mat(rawNumericColumns(:, 4));
    data.rx_init = cell2mat(rawNumericColumns(:, 5));
end
    
function raw = import_numeric_data(dataArray, cols)

    % Convert the contents of columns containing numeric text to numbers.
    % Replace non-numeric text with NaN.
    raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
    for col=1:length(dataArray)-1
        raw(1:length(dataArray{col}),col) = dataArray{col};
    end
    numericData = NaN(size(dataArray{1},1),size(dataArray,2));

    for col=cols
        % Converts text in the input cell array to numbers. Replaced non-numeric
        % text with NaN.
        rawData = dataArray{col};
        for row=1:size(rawData, 1)
            % Create a regular expression to detect and remove non-numeric prefixes and
            % suffixes.
            regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
            try
                result = regexp(rawData{row}, regexstr, 'names');
                numbers = result.numbers;

                % Detected commas in non-thousand locations.
                invalidThousandsSeparator = false;
                if any(numbers==',')
                    thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                    if isempty(regexp(numbers, thousandsRegExp, 'once'))
                        numbers = NaN;
                        invalidThousandsSeparator = true;
                    end
                end
                % Convert numeric text to numbers.
                if ~invalidThousandsSeparator
                    numbers = textscan(strrep(numbers, ',', ''), '%f');
                    numericData(row, col) = numbers{1};
                    raw{row, col} = numbers{1};
                end
            catch me
            end
        end
    end
end